#
# Copyright(C) 2013 Robinson Mittmann. All Rights Reserved.
# 
# This file is part of the YARD-ICE.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3.0 of the License, or (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You can receive a copy of the GNU Lesser General Public License from 
# http://www.gnu.org/

#
# File:   Makefile
# Author: Robinson Mittmann <bobmittmann@gmail.com>
# 


LIB_STATIC = cmx

SFILES = cmx-vec.S cmx-crt0.S\
	cmx_irq0.S cmx_irq1.S cmx_irq2.S cmx_irq3.S cmx_irq4.S\
	cmx_irq5.S cmx_irq6.S cmx_irq7.S cmx_irq8.S cmx_irq9.S\
	cmx_irq10.S cmx_irq11.S cmx_irq12.S cmx_irq13.S cmx_irq14.S\
	cmx_irq15.S cmx_irq16.S cmx_irq17.S cmx_irq18.S cmx_irq19.S\
	cmx_irq20.S cmx_irq21.S cmx_irq22.S cmx_irq23.S cmx_irq24.S\
	cmx_irq25.S cmx_irq26.S cmx_irq27.S cmx_irq28.S cmx_irq29.S\
	cmx_irq30.S cmx_irq31.S cmx_irq32.S cmx_irq33.S cmx_irq34.S\
	cmx_irq35.S cmx_irq36.S cmx_irq37.S cmx_irq38.S cmx_irq39.S\
	cmx_irq40.S cmx_irq41.S cmx_irq42.S cmx_irq43.S cmx_irq44.S\
	cmx_irq45.S cmx_irq46.S cmx_irq47.S cmx_irq48.S cmx_irq49.S\
	cmx_irq50.S cmx_irq51.S cmx_irq52.S cmx_irq53.S cmx_irq54.S\
	cmx_irq55.S cmx_irq56.S cmx_irq57.S cmx_irq58.S cmx_irq59.S\
	cmx_irq60.S cmx_irq61.S cmx_irq62.S cmx_irq63.S cmx_irq64.S\
	cmx_irq65.S cmx_irq66.S cmx_irq67.S cmx_irq68.S cmx_irq69.S\
	cmx_irq70.S cmx_irq71.S cmx_irq72.S cmx_irq73.S cmx_irq74.S\
	cmx_irq75.S cmx_irq76.S cmx_irq77.S cmx_irq78.S cmx_irq79.S\
	cmx_irq80.S cmx_irq81.S cmx_irq82.S cmx_irq83.S cmx_irq84.S\
	cmx_irq85.S cmx_irq86.S cmx_irq87.S cmx_irq88.S cmx_irq89.S\
	cmx_irq90.S cmx_irq91.S cmx_irq92.S cmx_irq93.S cmx_irq94.S\
	cmx_irq95.S cmx_irq96.S cmx_irq97.S cmx_irq98.S cmx_irq99.S\
	cmx_irq100.S cmx_irq101.S cmx_irq102.S cmx_irq103.S cmx_irq104.S\
	cmx_irq105.S cmx_irq106.S cmx_irq107.S cmx_irq108.S cmx_irq109.S\
	cmx_irq110.S cmx_irq111.S cmx_irq112.S cmx_irq113.S cmx_irq114.S\
	cmx_irq115.S cmx_irq116.S cmx_irq117.S cmx_irq118.S cmx_irq119.S\
	cmx_irq120.S cmx_irq121.S cmx_irq122.S cmx_irq123.S cmx_irq124.S\
	cmx_irq125.S cmx_irq126.S cmx_irq127.S 

include ../../../mk/config.mk
include ../../../mk/lib.mk
