# File:		Makefile
# Author:   Robinson Mittmann (bobmittmann@gmail.com)
# Target:
# Comment:  
# Copyright(C) 2012 Bob Mittmann. All Rights Reserved.
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 

include ../../mk/config.mk

LIB_STATIC = ice-comm

CFILES = ice-comm.c ice-io.c ice-comm_wr32.c \
		 ice-trace_init.c ice-trace0.c ice-trace1.c \
		 ice-trace2.c ice-trace3.c ice-trace4.c ice-trace5.c ice-trace6.c \
		 ice-trace7.c ice-trace8.c ice-trace9.c ice-trace10.c ice-tracestr.c \
		 ice-tracebin.c 

include ../../mk/lib.mk

