# File:		Makefile
# Module: 
# Target:
# Comment:  
# Copyright(C) 2012 Bob Mittmann. All Rights Reserved.
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 


PROG = u2s-485

CFILES = u2s-485.c serial.c board.c leds.c usb_trace.c raw_trace.c \
		 sdu_trace.c xflash.c usb_xflash_pic.c profclk.c

LIBDIRS = ../../sdk/libstm32f ../../sdk/libutil \
		  ../../sdk/libthinkos ../../sdk/libc ../../sdk/libice-comm \
		  ../../sdk/libcdc-acm 

LIBS = stm32f util thinkos c ice-comm cdc-acm 

CFLAGS = -Os

MACH = stm32f103x6
include ../../mk/stm32f103-krn.mk

