/*---------------------------------------------------------------------------
  This file was automatically generated by mkcmd.py. DO NOT edit!
  ---------------------------------------------------------------------------*/

#include <stdlib.h>
#include <string.h>
#include "cmdtab.h"

const char * const cmd_sym_tab[] = {
	[CMD_APP] = "app",
	[CMD_ERASE] = "erase",
	[CMD_HELP] = "help",
	[CMD_INFO] = "info",
	[CMD_RCVY] = "rcvy",
	[CMD_REBOOT] = "reboot",
	[CMD_TEST] = "test",
};

const char * const cmd_brief_tab[] = {
	[CMD_APP] = "Run the application",
	[CMD_ERASE] = "Erase application",
	[CMD_HELP] = "Display a list of commands",
	[CMD_INFO] = "Display system information",
	[CMD_RCVY] = "YMODEM app upload",
	[CMD_REBOOT] = "Reboot the system",
	[CMD_TEST] = "Perform a test",
};

const char cmd_alias_tab[][4] = {
	[CMD_APP] = "",
	[CMD_ERASE] = "e",
	[CMD_HELP] = "h",
	[CMD_INFO] = "i",
	[CMD_RCVY] = "y",
	[CMD_REBOOT] = "",
	[CMD_TEST] = "t",
};

const char * const cmd_param_tab[] = {
	[CMD_APP] = NULL,
	[CMD_ERASE] = NULL,
	[CMD_HELP] = "CMD",
	[CMD_INFO] = NULL,
	[CMD_RCVY] = NULL,
	[CMD_REBOOT] = NULL,
	[CMD_TEST] = NULL,
};

const cmd_callback_t cmd_call_tab[] = {
	[CMD_APP] = cmd_app,
	[CMD_ERASE] = cmd_erase,
	[CMD_HELP] = cmd_help,
	[CMD_INFO] = cmd_info,
	[CMD_RCVY] = cmd_rcvy,
	[CMD_REBOOT] = cmd_reboot,
	[CMD_TEST] = cmd_test,
};

/*
   List search...
*/

int cmd_lookup(const char * str)
{
	int i;

	for (i = CMD_FIRST; i <= CMD_LAST; ++i) {
		if (strcmp(str, cmd_sym_tab[i]) == 0)
			return i;
		if (strcmp(str, cmd_alias_tab[i]) == 0)
			return i;
	}

	return -1;
}

int cmd_first()
{
	return CMD_FIRST;
}

int cmd_last()
{
	return CMD_LAST;
}

const char * cmd_name(unsigned int code)
{
	return cmd_sym_tab[code];
}

const char * cmd_alias(unsigned int code)
{
	return cmd_alias_tab[code];
}

const char * cmd_brief(unsigned int code)
{
	return cmd_brief_tab[code];
}

int cmd_call(int argc, char * argv[], unsigned int code)
{
	if (code > CMD_LAST)
		return -1;
	return cmd_call_tab[code](argc, argv);
}

