/*---------------------------------------------------------------------------
  This file was automatically generated by mkcmd.py. DO NOT edit!
  ---------------------------------------------------------------------------*/

#ifndef __CMDTAB_H__
#define __CMDTAB_H__

#include <stdint.h>

#define CMD_APP         1
#define CMD_ERASE       2
#define CMD_HELP        3
#define CMD_INFO        4
#define CMD_RCVY        5
#define CMD_REBOOT      6
#define CMD_TEST        7

#define CMD_FIRST 1
#define CMD_LAST 7

typedef int(* cmd_callback_t)(int argc, char * argv[]);

extern const char * const cmd_sym_tab[];
extern const char * const cmd_brief_tab[];
extern const char * const cmd_desc_tab[];
extern const char cmd_alias_tab[][4];

extern const cmd_callback_t cmd_call_tab[];

#ifdef __cplusplus
extern "C" {
#endif

int cmd_lookup(const char * str);

int cmd_first();

int cmd_last();

const char * cmd_name(unsigned int code);

const char * cmd_alias(unsigned int code);

const char * cmd_brief(unsigned int code);

const char * cmd_detail(unsigned int code);

int cmd_call(int argc, char * argv[], unsigned int code);
/*---------------------------------------------------------------------------
  Callbacks!
  ---------------------------------------------------------------------------*/

int cmd_app(int argc, char * argv[]);
int cmd_erase(int argc, char * argv[]);
int cmd_help(int argc, char * argv[]);
int cmd_info(int argc, char * argv[]);
int cmd_rcvy(int argc, char * argv[]);
int cmd_reboot(int argc, char * argv[]);
int cmd_test(int argc, char * argv[]);

#ifdef __cplusplus
}
#endif

#endif /* __CMDTAB_H__ */

