
PROG = mbuf_test

CFILES = mbuf_test.c

MACH = stm32f207

LIBDIRS = ../../libcm3 ../../libstm32f ../../libutil ../../libthinkos ../../libc \
		  ../../libice-comm ../../libmbuf

LIBS = stm32f cm3 util thinkos c ice-comm mbuf

CFLAGS = -g -O2 

JTAGTOOL_ADDR = 192.168.1.30

include ../../../mk/stm32f207.mk

