/*---------------------------------------------------------------------------
  This file was automatically generated by mkcmd.py. DO NOT edit!
  ---------------------------------------------------------------------------*/

#include <stdlib.h>
#include <string.h>
#include "cmd_tab.h"


const char * const boot_cmd_sym_tab[] = {
	[BOOT_CMD_APP] = "app",
	[BOOT_CMD_ERASE] = "erase",
	[BOOT_CMD_HELP] = "help",
	[BOOT_CMD_INFO] = "info",
	[BOOT_CMD_RCVY] = "rcvy",
	[BOOT_CMD_REBOOT] = "reboot",
};

const char * const boot_cmd_brief_tab[] = {
	[BOOT_CMD_APP] = "Run the application",
	[BOOT_CMD_ERASE] = "Erase application",
	[BOOT_CMD_HELP] = "Display a list of commands",
	[BOOT_CMD_INFO] = "Display system information",
	[BOOT_CMD_RCVY] = "YMODEM app upload",
	[BOOT_CMD_REBOOT] = "Reboot the system",
};

const char boot_cmd_alias_tab[][4] = {
	[BOOT_CMD_APP] = "",
	[BOOT_CMD_ERASE] = "e",
	[BOOT_CMD_HELP] = "h",
	[BOOT_CMD_INFO] = "i",
	[BOOT_CMD_RCVY] = "y",
	[BOOT_CMD_REBOOT] = "",
};

const boot_cmd_callback_t boot_cmd_call_tab[] = {
	[BOOT_CMD_APP] = boot_cmd_app,
	[BOOT_CMD_ERASE] = boot_cmd_erase,
	[BOOT_CMD_HELP] = boot_cmd_help,
	[BOOT_CMD_INFO] = boot_cmd_info,
	[BOOT_CMD_RCVY] = boot_cmd_rcvy,
	[BOOT_CMD_REBOOT] = boot_cmd_reboot,
};

int boot_cmd_lookup(const char * str)
{
	int i;

	for (i = BOOT_CMD_FIRST; i <= BOOT_CMD_LAST; ++i) {
		if (strcmp(str, boot_cmd_sym_tab[i]) == 0)
			return i;
		if (strcmp(str, boot_cmd_alias_tab[i]) == 0)
			return i;
	}

	return -1;
}

