/*---------------------------------------------------------------------------
  This file was automatically generated by bin2hex.py
  ---------------------------------------------------------------------------*/

#ifndef __ICE40HX1K_H__
#define __ICE40HX1K_H__

/* --- bin2hex.py: file size --- */

#define SIZEOF_ICE40HX1K_BIN 2066


/* --- bin.hex.py: file content --- */

extern const uint8_t ice40hx1k_bin[];


#endif /* __ICE40HX1K_H__ */ 

