# $Id: Makefile,v 2.9 2008/06/04 00:03:14 bob Exp $ 
#
# File:		Makefile
# Module:	
# Project:	
# Author:	Robinson Mittmann (bob@boreste.com, bob@methafora.com.br)
# Target:	
# Comment:
# Copyright(c) 2003-2009 BORESTE (www.boreste.com). All Rights Reserved.

LIB_STATIC = mbuf

CFILES = mbuf.c mbuf_memavail.c mbuf_alloc.c mbuf_try_alloc.c\
		 mbuf_try_alloc_and_wait.c mbuf_free.c mbuf_check.c\
		 mbuf_size.c mbuf_avail.c mbuf_max.c mbuf_used.c mbuf_wait.c\
		 mbuf_list_alloc.c mbuf_list_free.c mbuf_list_read.c mbuf_list_write.c\
		 mbuf_queue_add.c mbuf_queue_free.c mbuf_queue_get.c\
		 mbuf_queue_init.c mbuf_queue_remove.c mbuf_queue_trim.c

include ../../mk/lib.mk

