/*---------------------------------------------------------------------------
  This file was automatically generated by bin2hex.py
  ---------------------------------------------------------------------------*/

#ifndef __MP3LIB_H__
#define __MP3LIB_H__

/* --- bin2hex.py: file size --- */

#define SIZEOF_VAEMBORA_MP3 12897

#define SIZEOF_BELL1_MP3 14733

#define SIZEOF_BATATINHA_MP3 39385

#define SIZEOF_ENTRE_MP3 15091

#define SIZEOF_AMORA_MP3 7881

#define SIZEOF_CASA_MP3 21988


/* --- bin.hex.py: file content --- */

extern const uint8_t vaembora_mp3[];

extern const uint8_t bell1_mp3[];

extern const uint8_t batatinha_mp3[];

extern const uint8_t entre_mp3[];

extern const uint8_t amora_mp3[];

extern const uint8_t casa_mp3[];


#endif /* __MP3LIB_H__ */ 
