/*---------------------------------------------------------------------------
  This file was automatically generated by bin2hex.py
  ---------------------------------------------------------------------------*/

#ifndef __MUSIC_H__
#define __MUSIC_H__

/* --- bin2hex.py: file size --- */

#define SIZEOF_MUSIC_MP3 96847


/* --- bin.hex.py: file content --- */

extern const uint8_t music_mp3[];


#endif /* __MUSIC_H__ */ 

