/*---------------------------------------------------------------------------
  This file was automatically generated by bin2hex.py
  ---------------------------------------------------------------------------*/

#ifndef __VOICE_H__
#define __VOICE_H__

/* --- bin2hex.py: file size --- */

#define SIZEOF_VOICE_MP3 7881


/* --- bin.hex.py: file content --- */

extern const uint8_t voice_mp3[];


#endif /* __VOICE_H__ */ 
