# File:		Makefile
# Module: 
# Target:
# Comment:  
# Copyright(C) 2012 Bob Mittmann. All Rights Reserved.
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 

SDK = ../../../../sdk

LIBDIRS =  $(SDK)/libcm3 $(SDK)/libstm32f $(SDK)/libstm32drv \
		   $(SDK)/libutil $(SDK)/libc $(SDK)/libconsole \
		   $(SDK)/libcrc \
		   $(SDK)/libtty $(SDK)/libshell $(SDK)/libtrace \
		   $(SDK)/libxmodem $(SDK)/libhexdump

INCPATH = $(SDK)/include ../../include

CDEFS = CONFIG_H
CFLAGS = -g -Og -fno-omit-frame-pointer -Wall
O := .

MACH = stm32f446xe
HSE_HZ = 12000000
THINKAPP = 1
include ../../../../mk/stm32f446x.mk
